---
version: "3.8"
services:
  wpp:
    build:
      context: ./wpp
    ports:
      - 3010:3010
    volumes:
      - ./tokens:/app/tokens
      - ./config.json:/app/config.json
    restart: unless-stopped
  sorter:
    build:
      context: ./processors
    depends_on:
      queue:
        condition: service_healthy
    restart: unless-stopped
    command: ["node", "sorter.js"]
  rule_processor:
    build:
      context: ./processors
    volumes:
      - ./rules/:/app/rules/
        #depends_on:
      #  queue:
      #condition: service_healthy
          # restart: true
    command: ["node", "ruleBasedProcessor"]
    restart: unless-stopped
  logger:
    build:
      context: ./processors
    command: ["node", "logger.js"]
    volumes:
      #- log:/app/log
      - ./log:/app/log
        #    depends_on:
        #queue:
        #condition: service_healthy
        #restart: true
    restart: unless-stopped
  downloader:
    build:
      context: ./processors
    command: ["node", "mediaDownloader.js"]
    volumes:
      #- media:/app/media
      - ./media:/app/media
        #depends_on:
      #      queue:
      #  condition: service_healthy
      #  restart: true
    restart: unless-stopped
  transcriber:
    build:
      context: ./processors
      dockerfile: Dockerfile.transcriber
    command: ["node", "transcriber.js"]
    volumes:
      - ./config.json:/app/config.json
      #    depends_on:
      #queue:
      #  condition: service_healthy
      #  restart: true
      # whisper:
      #  condition: service_started
    restart: unless-stopped
  queue:
    image: rabbitmq:management-alpine
    hostname: queue-server
    ports:
      - 15672:15672
      - 25672:5672
    volumes:
      - qv:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "netstat -antp | grep 5672"]
    restart: unless-stopped
  whisper:
    build:
      context: ./whisper
    ports:
      - 8099:8099
    restart: unless-stopped
volumes:
  qv:
  log:
  media:
