---
version: "3.8"
services:
  loro:
    build:
      context: ./venom-http
    ports:
      - 3010:3010
    depends_on:
      - whisper

  whisper:
    build:
      context: ./whisper
    ports:
      - 8099:8099
    