FROM ubuntu AS build
WORKDIR /app

RUN apt-get update && \
  apt-get install -y gnupg wget && \
  apt-key del 7fa2af80 && \
  wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/$(uname -m)/cuda-keyring_1.1-1_all.deb -O /cuda-keyring_1.1-1_all.deb && \
  dpkg -i /cuda-keyring_1.1-1_all.deb

RUN apt-get update && \
  apt-get install -y build-essential curl git linux-headers-generic cuda-toolkit && \
  rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN git clone https://github.com/ggerganov/whisper.cpp.git /app

# Uncomment for Apple Silicon
# ENV UNAME_M=arm64
# ENV UNAME_p=arm
# ENV LLAMA_NO_METAL=1
ENV CUDA_DOCKER_ARCH=COMPUTE_75
ENV GGML_CUDA=1
RUN make -j server

RUN /app/models/download-ggml-model.sh large-v3
CMD ["/app/server", "-l", "pt", "-m", "/app/models/ggml-large-v3.bin", "--host", "0.0.0.0", "--port", "8080"]
